# Site settings
title: Jay Wu
email: arkhanwu@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Personal website and blog for Jay Wu 
baseurl: "http://jaywu.me" # the subpath of your site, e.g. /blog/

github_username:  jaywuYJ


markdown: redcarpet
