# Site settings
title: Jay Wu
email: arkhanwu@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Personal website and blog for Jay Wu 
baseurl: "/blog/" # the subpath of your site, e.g. /blog/
url: "http://jay.me" # the base hostname & protocol for your site
github_username:  jaywuYJ
permalink: /blog/:title

markdown: redcarpet
