# Site settings
title: Jay Wu
email: arkhanwu@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Personal website and blog for Jay Wu 
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://jaywu.me"
github_username:  jaywuYJ
permalink: /blog/:title

markdown: redcarpet

# Settings for comments helper
# Set 'provider' to the comment provider you want to use.
# Set 'provider' to false to turn commenting off globally.
#
comments :
  provider : disqus
  disqus :
    short_name : jaywuYJ

# Settings for analytics helper
# Set 'provider' to the analytics provider you want to use.
# Set 'provider' to false to turn analytics off globally.
#        
analytics :
  provider : google
  google : 
      tracking_id : 'UA-566959-1'

